config/routes.rb
Rails.application.routes.draw do
  # get 'bookmarks/new'
  # get 'bookmarks/create'
  # get 'bookmarks/destroy'
  # get 'lists/index'
  # get 'lists/show'
  # get 'lists/new'
  # get 'lists/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, path: '/lists', only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true

  validates :comment, length: { minimum: 6 } # comment cannot be shorter than 6 characters
  validates :movie_id, uniqueness: { scope: :list_id } # is unique for a given movie/list couple
end

app/models/list.rb
class List < ApplicationRecord
  # List model has one to many relationship with bookmarks
  # You can't delete a movie, if it is rererences in at least one bookmark
  # When you delete a list, it should delete all associated bookmarks, but not the movies referenced in other lists!
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validate :validate_cover_image

  has_one_attached :cover_image

  private

  def validate_cover_image
    return unless cover_image.attached?

    if !cover_image.blob.content_type.starts_with?('image/')
      cover_image.purge
      errors.add(:cover_image, 'must be an image')
    elsif cover_image.blob.byte_size > 5.megabytes
      cover_image.purge
      errors.add(:cover_image, 'size cannont exceed 5MB')
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  # Movie has one to many relationship with bookmarks though association
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build # build a new bookmark record associated with the list, don't need to use NEW
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to @list, notice: 'Bookmark created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to @bookmark.list, notice: 'Bookmark deleted', status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/:id
  def show
    @list = List.find(params[:id])
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # POST /lists
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= render 'shared/navbar' %>

<h1>New Bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all, label_method: :title, value_method: :id %>
  <%= f.input :comment %>
  <%= f.button :submit, 'Create Bookmark' , class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/navbar' %>
<div class="container mt-5">

<section class="bg-gradient bg-primary-gradient ">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Save Any Kind of Movies</h1>
      </div>
    </div>
  </div>
</section>

  <h1>All lists</h1>
  <ul>
    <% @lists.each do |list| %>
      <% if list.cover_image.attached?  %>
        <%= cl_image_tag list.cover_image.key, height: 300, width: 400, crop: :fill %>
      <% end %>
      <li> <%= link_to list.name, list_path(list)  %></li>
    <% end %>
  </ul>

  <%= link_to 'Create List', new_list_path, class: 'btn btn-primary' %>
</div>

app/views/lists/new.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">
  <%= simple_form_for @list, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
    <%= f.input :name, label_html: { class: 'col-sm-2 control-label' }, input_html: { class: 'form-control' } %>
    <%= f.input :cover_image, as: :file %>
    <%= f.button :submit, 'Create List', class: 'btn btn-primary mt-3' %>
  <% end %>

  <%= link_to 'View Lists', lists_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/lists/show.html.erb
<%= render 'shared/navbar' %>

<div class="container mt-5">
  <h1 class="text-center"><%= @list.name.capitalize %> Details</h1>

  <% if @list.cover_image.attached? %>
    <div class="text-center">
      <%= cl_image_tag @list.cover_image.key, height: 400, width: 800, crop: "fill" %>
    <div>
  <% end %>

  <p>Name: <%= @list.name %></p>

  <h2>Bookmarks</h2>

  <% @list.bookmarks.each do |bookmark| %>
    <div>
      <p>Movie: <%= bookmark.movie.title %></p>
      <%= image_tag bookmark.movie.poster_url %>
      <p>Comment: <%= bookmark.comment %></p>
      <%= link_to 'Delete', bookmark_path(bookmark), data: { turbo_method: :delete,  turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    </div>
  <% end %>

  <p><%= link_to 'Add Bookmark', new_list_bookmark_path(@list) %></p>

  <div>
    <%= link_to 'Back to Lists', lists_path %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light fixed-top bg-light">
  <%= link_to 'Watch List Wonder', lists_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="ms-auto">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to 'Home', lists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'My lists', lists_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'New List', new_list_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</div>